---

- name: EC2 and nginx
  hosts: local
  connection: local
  
  vars:
    key_name: my_aws
    region: us-east-2
    security_group: my-security-group
    image: ami-0d03add87774b12c5
    instance_type: t2.micro
  
  
  
  tasks:
  - name: Upload key to AWS
    ec2_key:
      name: "{{ key_name }}"
      key_material: "{{ lookup('file', '/root/.ssh/{{ key_name }}.pub') }}"
      region: "{{ region }}"
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
  - name: Create security group
    ec2_group:
      name: "{{ security_group }}"
      description: My security grop made by Ansible
      region: "{{ region }}"
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Create EC2 instance
    ec2:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      key_name: "{{ key_name }}"
      group: "{{ security_group }}"
      image: "{{ image }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      user_data:
         |
         #!/bin/bash
         sudo apt update 
         sudo apt install nginx -y
         sudo service nginx start
      count: 1
      wait: true
