---

- name: Provision
  hosts: local
  connection: local
  
  vars:
    instance_type: t2.micro
    security_group: my_security_group
    image: ami-02ccb28830b645a41
    keypair: my_aws
    region: us-east-2
    count: 1
    
  tasks:
        
    - name: Create EC2 instance_type
      local_action: ec2
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        group={{ security_group }}
        instance_type={{ instance_type }}
        image={{ image }}
        wait=true
        wait_timeout=500        
        region={{ region }} 
        keypair={{ my_aws }}
        count={{count}}
        assign_public_ip: True               